<html>
<head>	
  <title>Hello Team Pwned </title>
</head>
  <body>
    <h1>>Hello Team Pwned</h1>

    <br><font size=+1>This program was generated by PHP programming language</font></br>
    <br>Current TIme: ', time.ctime(), '</br>

    <br>Your current IP address is: ', os.getenv("REMOTE_ADDR"), '</br>
  </body>
</html>